// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CashCloseController from "./cash_close_controller"
application.register("cash-close", CashCloseController)

import ComboboxController from "./combobox_controller"
application.register("combobox", ComboboxController)

import ConfirmController from "./confirm_controller"
application.register("confirm", ConfirmController)

import DismissController from "./dismiss_controller"
application.register("dismiss", DismissController)

import HistoryBackController from "./history_back_controller"
application.register("history-back", HistoryBackController)

import KitchenChimeController from "./kitchen_chime_controller"
application.register("kitchen-chime", KitchenChimeController)

import MenuSearchController from "./menu_search_controller"
application.register("menu-search", MenuSearchController)

import MobileNavController from "./mobile_nav_controller"
application.register("mobile-nav", MobileNavController)

import PosCartController from "./pos_cart_controller"
application.register("pos-cart", PosCartController)

import PrintPromptController from "./print_prompt_controller"
application.register("print-prompt", PrintPromptController)

import SlugSuggestController from "./slug_suggest_controller"
application.register("slug-suggest", SlugSuggestController)

import ValidateController from "./validate_controller"
application.register("validate", ValidateController)
