// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DismissController from "./dismiss_controller"
application.register("dismiss", DismissController)

import ValidateController from "./validate_controller"
application.register("validate", ValidateController)

import ConfirmController from "./confirm_controller"
application.register("confirm", ConfirmController)

import ComboboxController from "./combobox_controller"
application.register("combobox", ComboboxController)

import PosCartController from "./pos_cart_controller"
application.register("pos-cart", PosCartController)

import CashCloseController from "./cash_close_controller"
application.register("cash-close", CashCloseController)
